# lightning.pytorch==2.2.1
seed_everything: 42

data:
  class_path: dataset_utils.LightningDataModules.Era2CerraDataModule
  init_args:
    data_path:  data/  #Path to your dataset
    downscaling_factor: 1
    num_workers: 8
    batch_size:  8
    crop_size_era: 35
    crop_size_cerra: 140
    channel_names: [ 'pm2p5', 'blh', 'u10', 'v10', 'd2m', 't2m']
    use_separate_dataset: true
    constant_channels: true
    return_offset: true
    return_era_original: false
    transform: True
    standarized: True

model:
  ##LightweightSwinFIR
  class_path: models.swin_fir.swin_fir.SwinFIR_sidechannel
  init_args:   
    results_dir: null
    learning_rate: 1.5e-4
    img_size: 35
    window_size: 7
    img_range: 1.
    depths: [5,5,5,5,5] # [6,5,5,6]
    embed_dim: 220
    num_heads: [6,6,6,6,6]
    mlp_ratio: 2
    upscale: 4
    upsampler: "pixelshuffledirect"
    in_chans: 6
    out_chans: 1
    resi_connection: 'HSFB'
    num_sidechannels: 2
    embed_dim_sidechannels: 20
    loss_beta: 0.6
    ape: false
    full_height_cerra: 420
    full_width_cerra: 700   
    land_mask_bool: False 
    metrics_names: [ 'l1Error', 'l2Error', 'Bias_time', 'Bias_space', 'Corr_time', 'Corr_space', 'RMSE_time', 'RMSE_space', 'PeakSignalNoiseRatio', 'StructuralSimilarityIndexMeasure', 'UniversalImageQualityIndex']

trainer:

  #logger:
    #class_path: lightning.pytorch.loggers.tensorboard.TensorBoardLogger
    #init_args:
      #save_dir: "tb_logs"
      #name: "AirPollution_Full_Charbonier"
      #version: "LR_1p5e-5"
      #log_graph: False
      #default_hp_metric: true

  logger:
    class_path: WandbLogger ####Set your own username, etc.
    init_args:
      name: "AirPollution"
      project: "airpollution-downscaling-swin-fir"
      entity: "marcos-martinez-roig-universitat-de-val-ncia"
      group: "era2cerra"
      job_type: "train"
      tags: ['swinFIR', '4x', 'u10/v10']

  #logger:
    #class_path: lightning.pytorch.loggers.MLFlowLogger
    #init_args:
      #experiment_name: "AirPollution"
      #tracking_uri: "file:///ruta/a/tu/mlruns"  # Por ejemplo local
      #tags:
        #project: "airpollution-downscaling-swin-fir"
        #group: "era2cerra"
        #job_type: "train"


  accelerator: 'gpu' #Change to 'auto' for GPU
  fast_dev_run: false
    
  strategy: auto
  devices: auto
  num_nodes: 1
  precision: null
  max_epochs: 3
  min_epochs: null
  max_steps: -1
  min_steps: null
  max_time: "00:23:00:00"
  limit_train_batches: null
  limit_val_batches: null
  # limit_test_batches: 5
  limit_predict_batches: null
  overfit_batches: 0.0
  val_check_interval: 1.0
  check_val_every_n_epoch: 1
  num_sanity_val_steps: 0 #null
  log_every_n_steps: null
  enable_checkpointing: null
  enable_progress_bar: true
  enable_model_summary: true
  accumulate_grad_batches: 1
  gradient_clip_val: null
  gradient_clip_algorithm: null
  deterministic: null
  benchmark: null
  inference_mode: true
  profiler: null
  detect_anomaly: false
  barebones: false
  plugins: null
  sync_batchnorm: false
  reload_dataloaders_every_n_epochs: 0
  default_root_dir: null

default_lr_monitor:
  logging_interval: epoch
 
default_early_stopping:
  monitor: val_loss
  min_delta: 0.0
  patience: 100
  verbose: true
  mode: min
  strict: true
  check_finite: true
  stopping_threshold: null
  divergence_threshold: null
  check_on_train_epoch_end: null
  log_rank_zero_only: false

default_checkpoint:
  #dirpath: output/models
  #filename: example
  dirpath: null
  filename: "example-{epoch:02d}-{val_loss:.4f}"
  monitor: val_loss
  verbose: true
  save_last: true
  save_top_k: 1
  save_weights_only: false
  mode: min
  auto_insert_metric_name: true
  every_n_train_steps: null
  train_time_interval: null
  every_n_epochs: null
  save_on_train_epoch_end: null
  enable_version_counter: false



